### ISSUE TITLE
Duplicate user in project

### ISSUE THREAD

**Issue by tk-king** [edge-ml/backend#6]
Prevent duplicate user in projects.
A userId cannot be in the users list of a project multiple times.
When a user is admin of a project, this user cannot appear in the users list of the project.

**Comment by tk-king** [comment]
In the same sense, the application stops working when a user is part of a project and this user then gets deleted.

**Comment by tk-king** [comment]
- Prevented duplicate users in projects in the frontend, still needs to be done in the backend
- Prevent users from adding non - existent  users to projects

**Comment by TobiasRoeddiger** [comment]
Will have to prevent adding duplicte users in the backend.

Also if a user deletes its account, the project breaks for all users which in turn breaks it for everyone else.

**Comment by tk-king** [comment]
Deleting a useraccount which is registered in a project no longer breaks the project and the project gets updated to no longer include the deleted user.
